import { StoreProvider } from "@/lib/StoreProvider";
import localFont from "next/font/local";
import "./globals.css";
import DashNavBar from "@/components/DashNavBar";
import { cookies } from "next/headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const lang = cookieStore.get("lang")?.value || 'en';
  const dir = lang === "ar" ? "rtl" : "ltr"; 

  return (
    <html lang={lang} dir={dir}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <DashNavBar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
